# Testing my methodology

In [1]:
import os
# set the directory to the root
os.chdir("/Users/jeandurand/Documents/Masters Thesis/causal_bayes_opt")

import numpy as np
import pandas as pd
from graphs.toy_graph import ToyGraph
from graphs.graph_6_nodes import Graph6Nodes
from graphs.graph_erdos_renyi import ErdosRenyiGraph
from graphs.graph_chain import ChainGraph
from algorithms.PARENT_algorithm import PARENT
from graphs.data_setup import setup_observational_interventional

 /Users/jeandurand/Documents/Masters Thesis/causal_bayes_opt/ceo_venv/lib/python3.10/site-packages/tqdm/auto.py:21: TqdmWarning:IProgress not found. Please update jupyter and ipywidgets. See https://ipywidgets.readthedocs.io/en/stable/user_install.html
No GPU automatically detected. Setting SETTINGS.GPU to 0, and SETTINGS.NJOBS to cpu_count.


In [2]:
# graph = ErdosRenyiGraph(num_nodes=20)
graph = ChainGraph(num_nodes=20)
# graph = Graph6Nodes()
# graph = ToyGraph()

D_O, D_I, _ = setup_observational_interventional(graph_type=None, graph=graph, n_obs=1000, n_int=0)


INFO:root:Sampling the observational data
INFO:root:Sampling the interventional data


GT causal graph
[[0 1 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0]
 [0 0 1 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0]
 [0 0 0 1 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0]
 [0 0 0 0 1 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0]
 [0 0 0 0 0 1 0 0 0 0 0 0 0 0 0 0 0 0 0 0]
 [0 0 0 0 0 0 1 0 0 0 0 0 0 0 0 0 0 0 0 0]
 [0 0 0 0 0 0 0 1 0 0 0 0 0 0 0 0 0 0 0 0]
 [0 0 0 0 0 0 0 0 1 0 0 0 0 0 0 0 0 0 0 0]
 [0 0 0 0 0 0 0 0 0 1 0 0 0 0 0 0 0 0 0 0]
 [0 0 0 0 0 0 0 0 0 0 1 0 0 0 0 0 0 0 0 0]
 [0 0 0 0 0 0 0 0 0 0 0 1 0 0 0 0 0 0 0 0]
 [0 0 0 0 0 0 0 0 0 0 0 0 1 0 0 0 0 0 0 0]
 [0 0 0 0 0 0 0 0 0 0 0 0 0 1 0 0 0 0 0 0]
 [0 0 0 0 0 0 0 0 0 0 0 0 0 0 1 0 0 0 0 0]
 [0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 1 0 0 0 0]
 [0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 1 0 0 0]
 [0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 1 0 0]
 [0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 1 0]
 [0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 1]
 [0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0]]


In [3]:
my_algo = PARENT(graph)
my_algo.set_values(D_O, D_I)
my_algo.run_algorithm()

(500, 18) (500, 18) (500,) (500,) (500, 1) (500, 1)
(500, 18) (500, 18) (500,) (500,) (500, 1) (500, 1)
(500, 18) (500, 18) (500,) (500,) (500, 1) (500, 1)
(500, 18) (500, 18) (500,) (500,) (500, 1) (500, 1)
(500, 18) (500, 18) (500,) (500,) (500, 1) (500, 1)
(500, 18) (500, 18) (500,) (500,) (500, 1) (500, 1)
(500, 18) (500, 18) (500,) (500,) (500, 1) (500, 1)
(500, 18) (500, 18) (500,) (500,) (500, 1) (500, 1)
(500, 18) (500, 18) (500,) (500,) (500, 1) (500, 1)
(500, 18) (500, 18) (500,) (500,) (500, 1) (500, 1)
(500, 18) (500, 18) (500,) (500,) (500, 1) (500, 1)
(500, 18) (500, 18) (500,) (500,) (500, 1) (500, 1)
(500, 18) (500, 18) (500,) (500,) (500, 1) (500, 1)
(500, 18) (500, 18) (500,) (500,) (500, 1) (500, 1)
(500, 18) (500, 18) (500,) (500,) (500, 1) (500, 1)
(500, 18) (500, 18) (500,) (500,) (500, 1) (500, 1)
(500, 18) (500, 18) (500,) (500,) (500, 1) (500, 1)
(500, 18) (500, 18) (500,) (500,) (500, 1) (500, 1)
(500, 18) (500, 18) (500,) (500,) (500, 1) (500, 1)
(500, 18) (5

In [7]:
print(D_O)

{'0': array([[-0.01543337],
       [-0.23155302],
       [-0.05530052],
       ...,
       [ 0.11547091],
       [ 0.06648022],
       [ 0.09932371]]), '1': array([[-0.12541208],
       [-0.31293732],
       [ 0.12351043],
       ...,
       [-0.15053354],
       [ 0.15849444],
       [ 0.05943857]]), '2': array([[-0.37476323],
       [ 0.73622575],
       [ 0.76924966],
       ...,
       [-0.05107505],
       [ 0.38177975],
       [-0.88448867]]), '3': array([[-1.27573059],
       [ 1.22122717],
       [ 0.64600996],
       ...,
       [-0.2203009 ],
       [ 0.64332982],
       [-1.03420871]]), '4': array([[-2.25385921],
       [ 4.17253082],
       [ 2.90353863],
       ...,
       [ 0.1469845 ],
       [ 1.3952026 ],
       [-3.19021173]]), '5': array([[-6.10994558],
       [ 8.49796938],
       [ 4.52695903],
       ...,
       [ 0.4195076 ],
       [ 1.3068553 ],
       [-6.32154267]]), '6': array([[-11.53519466],
       [ 18.96866486],
       [  8.12763797],
       ...,
       